BEGIN;

CREATE TABLE IF NOT EXISTS group_scraps (
    group_scrap_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    group_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_group_scraps_user_group UNIQUE (user_id, group_id),
    CONSTRAINT fk_group_scraps_user
        FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT fk_group_scraps_group
        FOREIGN KEY (group_id) REFERENCES groups (group_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_group_scraps_user_created
    ON group_scraps (user_id, created_at DESC, group_scrap_id DESC);
CREATE UNIQUE INDEX IF NOT EXISTS uk_group_scraps_user_group
    ON group_scraps (user_id, group_id);

CREATE TABLE IF NOT EXISTS event_scraps (
    event_scrap_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_event_scraps_user_event UNIQUE (user_id, event_id),
    CONSTRAINT fk_event_scraps_user
        FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT fk_event_scraps_event
        FOREIGN KEY (event_id) REFERENCES events (event_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_event_scraps_user_created
    ON event_scraps (user_id, created_at DESC, event_scrap_id DESC);
CREATE UNIQUE INDEX IF NOT EXISTS uk_event_scraps_user_event
    ON event_scraps (user_id, event_id);

-- Hibernate가 테이블을 먼저 만든 환경에서도 기존 FK의 삭제 규칙을 CASCADE로 교정한다.
DO $$
DECLARE
    fk_name TEXT;
BEGIN
    FOR fk_name IN
        SELECT conname
        FROM pg_constraint
        WHERE conrelid = 'group_scraps'::regclass
          AND contype = 'f'
          AND array_length(conkey, 1) = 1
          AND EXISTS (
              SELECT 1
              FROM unnest(conkey) AS key(attnum)
              JOIN pg_attribute AS attribute
                ON attribute.attrelid = 'group_scraps'::regclass
               AND attribute.attnum = key.attnum
              WHERE attribute.attname IN ('user_id', 'group_id')
          )
    LOOP
        EXECUTE format('ALTER TABLE group_scraps DROP CONSTRAINT %I', fk_name);
    END LOOP;
END
$$;

ALTER TABLE group_scraps
    ADD CONSTRAINT fk_group_scraps_user
        FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE,
    ADD CONSTRAINT fk_group_scraps_group
        FOREIGN KEY (group_id) REFERENCES groups (group_id) ON DELETE CASCADE;

DO $$
DECLARE
    fk_name TEXT;
BEGIN
    FOR fk_name IN
        SELECT conname
        FROM pg_constraint
        WHERE conrelid = 'event_scraps'::regclass
          AND contype = 'f'
          AND array_length(conkey, 1) = 1
          AND EXISTS (
              SELECT 1
              FROM unnest(conkey) AS key(attnum)
              JOIN pg_attribute AS attribute
                ON attribute.attrelid = 'event_scraps'::regclass
               AND attribute.attnum = key.attnum
              WHERE attribute.attname IN ('user_id', 'event_id')
          )
    LOOP
        EXECUTE format('ALTER TABLE event_scraps DROP CONSTRAINT %I', fk_name);
    END LOOP;
END
$$;

ALTER TABLE event_scraps
    ADD CONSTRAINT fk_event_scraps_user
        FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE,
    ADD CONSTRAINT fk_event_scraps_event
        FOREIGN KEY (event_id) REFERENCES events (event_id) ON DELETE CASCADE;

COMMIT;
