BEGIN;

CREATE TABLE IF NOT EXISTS group_inquiries (
    group_inquiry_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    author_user_id BIGINT NOT NULL,
    content VARCHAR(1000) NOT NULL,
    answer_content VARCHAR(1000),
    created_at TIMESTAMPTZ NOT NULL,
    answered_at TIMESTAMPTZ,
    CONSTRAINT ck_group_inquiries_answer
        CHECK (
            (answer_content IS NULL AND answered_at IS NULL)
            OR (answer_content IS NOT NULL AND answered_at IS NOT NULL)
        ),
    CONSTRAINT fk_group_inquiries_group
        FOREIGN KEY (group_id) REFERENCES groups (group_id) ON DELETE CASCADE,
    CONSTRAINT fk_group_inquiries_author
        FOREIGN KEY (author_user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_group_inquiries_group_created
    ON group_inquiries (group_id, created_at DESC, group_inquiry_id DESC);

-- Hibernate가 테이블을 먼저 만든 환경에서도 답변 정합성 CHECK를 멱등 보강한다.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conrelid = 'group_inquiries'::regclass
          AND conname = 'ck_group_inquiries_answer'
    ) THEN
        ALTER TABLE group_inquiries
            ADD CONSTRAINT ck_group_inquiries_answer
                CHECK (
                    (answer_content IS NULL AND answered_at IS NULL)
                    OR (answer_content IS NOT NULL AND answered_at IS NOT NULL)
                );
    END IF;
END
$$;

-- Hibernate가 만든 기존 FK도 대상 삭제 시 문의가 정리되도록 CASCADE로 교정한다.
DO $$
DECLARE
    fk_name TEXT;
BEGIN
    FOR fk_name IN
        SELECT DISTINCT constraint_info.conname
        FROM pg_constraint AS constraint_info
        JOIN unnest(constraint_info.conkey) AS key(attnum) ON TRUE
        JOIN pg_attribute AS attribute
          ON attribute.attrelid = constraint_info.conrelid
         AND attribute.attnum = key.attnum
        WHERE constraint_info.conrelid = 'group_inquiries'::regclass
          AND constraint_info.contype = 'f'
          AND attribute.attname IN ('group_id', 'author_user_id')
    LOOP
        EXECUTE format('ALTER TABLE group_inquiries DROP CONSTRAINT %I', fk_name);
    END LOOP;
END
$$;

ALTER TABLE group_inquiries
    ADD CONSTRAINT fk_group_inquiries_group
        FOREIGN KEY (group_id) REFERENCES groups (group_id) ON DELETE CASCADE,
    ADD CONSTRAINT fk_group_inquiries_author
        FOREIGN KEY (author_user_id) REFERENCES users (user_id) ON DELETE CASCADE;

COMMIT;
