BEGIN;

CREATE TABLE IF NOT EXISTS event_applications (
    event_application_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    applied_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_event_applications_user_event UNIQUE (user_id, event_id),
    CONSTRAINT fk_event_applications_user
        FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_event_applications_event
        FOREIGN KEY (event_id) REFERENCES events(event_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_event_applications_user_applied
    ON event_applications (user_id, applied_at, event_application_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_event_applications_user_event
    ON event_applications (user_id, event_id);

COMMIT;
