BEGIN;

SET LOCAL lock_timeout = '10s';
SET LOCAL statement_timeout = '60s';

CREATE TABLE IF NOT EXISTS chat_messages (
    message_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    sender_user_id BIGINT NOT NULL,
    content VARCHAR(2000) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS chat_read_states (
    read_state_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    last_read_message_id BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_chat_read_states_group_user UNIQUE (group_id, user_id),
    CONSTRAINT ck_chat_read_states_message_id CHECK (last_read_message_id >= 0)
);

CREATE INDEX IF NOT EXISTS idx_chat_messages_group_message
    ON chat_messages (group_id, message_id DESC);
CREATE UNIQUE INDEX IF NOT EXISTS uk_chat_read_states_group_user
    ON chat_read_states (group_id, user_id);

-- Hibernate가 먼저 만든 환경에서도 FK 삭제 규칙을 확정된 값으로 멱등 교정한다.
DO $$
DECLARE
    fk_name TEXT;
BEGIN
    FOR fk_name IN
        SELECT DISTINCT constraint_info.conname
        FROM pg_constraint AS constraint_info
        JOIN unnest(constraint_info.conkey) AS key(attnum) ON TRUE
        JOIN pg_attribute AS attribute
          ON attribute.attrelid = constraint_info.conrelid
         AND attribute.attnum = key.attnum
        WHERE constraint_info.conrelid = 'chat_messages'::regclass
          AND constraint_info.contype = 'f'
          AND attribute.attname IN ('group_id', 'sender_user_id')
    LOOP
        EXECUTE format('ALTER TABLE chat_messages DROP CONSTRAINT %I', fk_name);
    END LOOP;
END
$$;

ALTER TABLE chat_messages
    ADD CONSTRAINT fk_chat_messages_group
        FOREIGN KEY (group_id) REFERENCES groups (group_id) ON DELETE CASCADE,
    ADD CONSTRAINT fk_chat_messages_sender
        FOREIGN KEY (sender_user_id) REFERENCES users (user_id);

DO $$
DECLARE
    fk_name TEXT;
BEGIN
    FOR fk_name IN
        SELECT DISTINCT constraint_info.conname
        FROM pg_constraint AS constraint_info
        JOIN unnest(constraint_info.conkey) AS key(attnum) ON TRUE
        JOIN pg_attribute AS attribute
          ON attribute.attrelid = constraint_info.conrelid
         AND attribute.attnum = key.attnum
        WHERE constraint_info.conrelid = 'chat_read_states'::regclass
          AND constraint_info.contype = 'f'
          AND attribute.attname IN ('group_id', 'user_id')
    LOOP
        EXECUTE format('ALTER TABLE chat_read_states DROP CONSTRAINT %I', fk_name);
    END LOOP;
END
$$;

ALTER TABLE chat_read_states
    ADD CONSTRAINT fk_chat_read_states_group
        FOREIGN KEY (group_id) REFERENCES groups (group_id) ON DELETE CASCADE,
    ADD CONSTRAINT fk_chat_read_states_user
        FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'chat_read_states'::regclass
          AND conname = 'ck_chat_read_states_message_id'
    ) THEN
        ALTER TABLE chat_read_states
            ADD CONSTRAINT ck_chat_read_states_message_id CHECK (last_read_message_id >= 0);
    END IF;
END
$$;

-- 약속 장소 후보와 투표를 채팅 배포 마이그레이션에 함께 포함한다.
-- 운영 배포기는 이 파일 하나를 체크섬 기준으로 실행한다.
CREATE TABLE IF NOT EXISTS meetups (
    meetup_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    creator_user_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    meeting_date DATE NOT NULL,
    meeting_time TIME NOT NULL,
    status VARCHAR(20) NOT NULL,
    confirmed_option_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT ck_meetups_status CHECK (status IN ('OPEN', 'CONFIRMED', 'CANCELLED')),
    CONSTRAINT fk_meetups_group
        FOREIGN KEY (group_id) REFERENCES groups (group_id) ON DELETE CASCADE,
    CONSTRAINT fk_meetups_creator
        FOREIGN KEY (creator_user_id) REFERENCES users (user_id)
);

CREATE TABLE IF NOT EXISTS meetup_options (
    option_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meetup_id BIGINT NOT NULL,
    rank_order INTEGER NOT NULL,
    place_name VARCHAR(100) NOT NULL,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    address VARCHAR(255),
    phone VARCHAR(50),
    reason VARCHAR(500),
    CONSTRAINT fk_meetup_options_meetup
        FOREIGN KEY (meetup_id) REFERENCES meetups (meetup_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS meetup_votes (
    vote_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meetup_id BIGINT NOT NULL,
    option_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_meetup_votes_meetup_user UNIQUE (meetup_id, user_id),
    CONSTRAINT fk_meetup_votes_meetup
        FOREIGN KEY (meetup_id) REFERENCES meetups (meetup_id) ON DELETE CASCADE,
    CONSTRAINT fk_meetup_votes_option
        FOREIGN KEY (option_id) REFERENCES meetup_options (option_id) ON DELETE CASCADE,
    CONSTRAINT fk_meetup_votes_user
        FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_meetups_group_created
    ON meetups (group_id, created_at, meetup_id);
CREATE INDEX IF NOT EXISTS idx_meetup_options_meetup_rank
    ON meetup_options (meetup_id, rank_order, option_id);
CREATE UNIQUE INDEX IF NOT EXISTS uk_meetup_votes_meetup_user
    ON meetup_votes (meetup_id, user_id);

COMMIT;
